#!/bin/bash

cd /usr/share/skype

if ps -ef|grep -v grep|grep -q share/skype;then
  echo "Skype is already running"
  exit
fi
(
  rm -f ~/.Skype/Logs/skype*.log ~/.Skype/Logs/skype*.txt
  cd /usr/share/skype
  LD_PRELOAD=/usr/share/skype/lib32/libv4l/v4l2convert.so \
  GCONV_PATH=/usr/share/skype/lib32/gconv \
  QT_PLUGIN_PATH=/usr/share/skype/lib32/plugins \
  PULSE_LATENCY_MSEC=60 \
    /usr/share/skype/lib32/ld-linux.so.2 --library-path /usr/share/skype/lib32/ /usr/share/skype/skype 
  echo
  rm -f ~/.Skype/Logs/skype*.log ~/.Skype/Logs/skype*.txt &
) &
